insert into options(name, value, unit, id_parent) values ('Taille de l''écran' , '12.9' , 'pouces' , 5);
insert into options(name, value, unit, id_parent) values ('Taille de l''écran' , '11' , 'pouces' , 5);
insert into options(name, value, unit, id_parent) values ('Taille de l''écran' , '10.9' , 'pouces' , 5);
insert into options(name, value, unit, id_parent) values ('Taille de l''écran' , '10.2' , 'pouces' , 5);
insert into options(name, value, unit, id_parent) values ('Taille de l''écran' , '8.3' , 'pouces' , 5);
insert into options(name, value, unit, id_parent) values ('Taille de l''écran' , '13' , 'pouces' , 5);
insert into options(name, value, unit, id_parent) values ('Taille de l''écran' , '16' , 'pouces' , 5);
insert into options(name, value, unit, id_parent) values ('Taille de l''écran' , '27' , 'pouces' , 5);
insert into options(name, value, unit, id_parent) values ('Taille de l''écran' , '24.0' , 'pouces' , 5);