insert into mapped_prod_names(name) values("iPhone 11 PRO MAX");
insert into mapped_prod_names(name) values("iPhone 12 PRO MAX");
insert into mapped_prod_names(name) values("Cable Chargeur");
insert into mapped_prod_names(name) values("iPhone 12 Mini");
insert into mapped_prod_names(name) values("iPhone 13 Mini");
insert into mapped_prod_names(name) values("iPad Air 10.9");
insert into mapped_prod_names(name) values("iPad PRO 12.9");
insert into mapped_prod_names(name) values("iPhone 11 PRO");
insert into mapped_prod_names(name) values("iPhone 12 PRO");
insert into mapped_prod_names(name) values("iPhone 13 PRO");
insert into mapped_prod_names(name) values("iPhone 8 PLUS");
insert into mapped_prod_names(name) values("iPad PRO 11");
insert into mapped_prod_names(name) values("iPad 10.2");
insert into mapped_prod_names(name) values("iPad Mini");
insert into mapped_prod_names(name) values("iPhone 11");
insert into mapped_prod_names(name) values("iPhone 12");
insert into mapped_prod_names(name) values("iPhone 13");
insert into mapped_prod_names(name) values("iPhone Se");
insert into mapped_prod_names(name) values("iPhone 7");