insert into options(name, value , id_parent) values('Violet', 'Violet' , 1);
insert into options(name, value , id_parent) values('Bleu Alpin', 'Bleu Alpin' , 1);
insert into options(name, value , id_parent) values('Graphite', 'Graphite' , 1);
insert into options(name, value , id_parent) values('Or', 'Or' , 1);
insert into options(name, value , id_parent) values('Bleu Pacifique', 'Bleu Pacifique' , 1);
insert into options(name, value , id_parent) values('Argent', 'Argent' , 1);
insert into options(name, value , id_parent) values('Rose', 'Rose' , 1);
insert into options(name, value , id_parent) values('Bleu', 'Bleu' , 1);
insert into options(name, value , id_parent) values('Minuit', 'Minuit' , 1);
insert into options(name, value , id_parent) values('Noir', 'Noir' , 1);
insert into options(name, value , id_parent) values('Blanc', 'Blanc' , 1);
insert into options(name, value , id_parent) values('Rouge', 'Rouge' , 1);
insert into options(name, value , id_parent) values('Vert Nuit', 'Vert Nuit' , 1);
insert into options(name, value , id_parent) values('Vert', 'Vert' , 1);
insert into options(name, value , id_parent) values('Jaune', 'Jaune' , 1);
insert into options(name, value , id_parent) values('Gold', 'Gold' , 1);
insert into options(name, value , id_parent) values('Midnight', 'Midnight' , 1);
insert into options(name, value , id_parent) values('Pacific Blu', 'Pacific Blu' , 1);
insert into options(name, value , id_parent) values('Pink', 'Pink' , 1);
insert into options(name, value , id_parent) values('Gris', 'Gris' , 1);
insert into options(name, value , id_parent) values('Lumière Stellaire', 'Lumière Stellaire' , 1);