insert into brands(name, Specialite, description, logo) values ('10.or' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Acer' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Adcom' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Airtel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Alcatel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Alpha' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Amazon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('AOC' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Apple' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Aqua' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Archos' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Asus' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Benq' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Billion' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Black Shark' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('BlackBerry' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Blu' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('BQ' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Byond' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Cat' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Celkon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Centric' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Champion Computers' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('ChampOne' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Cherry Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Comio' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Coolpad' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Creo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Croma' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Datawind' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Detel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Dizo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Docoss' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Elari' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Elephone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Energizer' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Essential' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Evercoss' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Fairphone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Flash' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Fly' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('GeeksPhone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('General Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Gionee' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Google' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Homtom' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Honor' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('HP' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('HTC' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Huawei' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Hyve' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('i-mobiles' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('iBall' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('iBerry' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Idea' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Infinix' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('InFocus' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Intex' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('iQOO' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Itel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('iVoomi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Jio' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Jivi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Jolla' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Josh Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Karbonn' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Kestrel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Kodak' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Kult' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Kyocera' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Land Rover' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lava' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('LeEco' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Leica' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lemon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lenovo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lephone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('LG' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lumigon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lyf' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('M-tech' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Mafe Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Magicon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('MarQ by Flipkart' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Marshall' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Maxx Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Meizu' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Mercury' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Micromax' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Microsoft' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Mitashi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Mito' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Mobiistar' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Motorola' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('mPhone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('MTS' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('MyPhone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Namotel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Neffos' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Nexian' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Nextbit' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Nokia' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Nubia' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Nuu Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Obi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Obi Worldphone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('OnePlus' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Onida' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Oplus' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Oppo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Oukitel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Panasonic' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Pantel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Pepsi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Phicomm' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Philips' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Poco' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Polaroid' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Porsche Design' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('QiKU' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('QMobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Razer' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Reach' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Realme' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Reliance' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Ringing Bells' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Rio' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Royole' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Salora' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Samsung' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sansui' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Saygus' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sharp' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sikur' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Silent Circle' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Simmtronics' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sirin' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Smartisan' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Smartron' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sony' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Spice' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sunstrike' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Swipe' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Symphony' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Tambo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('TCL' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Tecno' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Tonino Lamborghini' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Turing' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Umi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Unihertz' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Vaio' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Vertu' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Viaan' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Videocon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Vivo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Vodafone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Wickedleak' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Wiio' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Xiaomi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Xolo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Yamada Denki' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Yandex' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Yota Devices' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Yu' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Zen' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Ziox' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Zopo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('ZTE' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Zuk' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Zync' , '["5"]' , '' , '');