delete from brands where 1 =1;
ALTER TABLE brands AUTO_INCREMENT = 1;

insert into brands(name, Specialite, description, logo) values ('10.or' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Acer' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Adcom' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Airtel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Alcatel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Alpha' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Amazon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('AOC' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Apple' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Aqua' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Archos' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Asus' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Benq' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Billion' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Black Shark' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('BlackBerry' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Blu' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('BQ' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Byond' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Cat' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Celkon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Centric' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Champion Computers' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('ChampOne' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Cherry Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Comio' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Coolpad' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Creo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Croma' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Datawind' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Detel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Dizo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Docoss' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Elari' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Elephone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Energizer' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Essential' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Evercoss' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Fairphone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Flash' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Fly' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('GeeksPhone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('General Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Gionee' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Google' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Homtom' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Honor' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('HP' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('HTC' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Huawei' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Hyve' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('i-mobiles' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('iBall' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('iBerry' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Idea' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Infinix' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('InFocus' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Intex' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('iQOO' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Itel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('iVoomi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Jio' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Jivi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Jolla' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Josh Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Karbonn' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Kestrel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Kodak' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Kult' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Kyocera' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Land Rover' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lava' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('LeEco' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Leica' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lemon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lenovo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lephone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('LG' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lumigon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Lyf' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('M-tech' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Mafe Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Magicon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('MarQ by Flipkart' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Marshall' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Maxx Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Meizu' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Mercury' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Micromax' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Microsoft' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Mitashi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Mito' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Mobiistar' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Motorola' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('mPhone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('MTS' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('MyPhone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Namotel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Neffos' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Nexian' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Nextbit' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Nokia' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Nubia' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Nuu Mobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Obi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Obi Worldphone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('OnePlus' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Onida' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Oplus' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Oppo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Oukitel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Panasonic' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Pantel' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Pepsi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Phicomm' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Philips' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Poco' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Polaroid' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Porsche Design' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('QiKU' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('QMobile' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Razer' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Reach' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Realme' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Reliance' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Ringing Bells' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Rio' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Royole' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Salora' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Samsung' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sansui' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Saygus' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sharp' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sikur' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Silent Circle' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Simmtronics' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sirin' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Smartisan' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Smartron' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sony' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Spice' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Sunstrike' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Swipe' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Symphony' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Tambo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('TCL' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Tecno' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Tonino Lamborghini' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Turing' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Umi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Unihertz' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Vaio' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Vertu' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Viaan' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Videocon' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Vivo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Vodafone' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Wickedleak' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Wiio' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Xiaomi' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Xolo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Yamada Denki' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Yandex' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Yota Devices' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Yu' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Zen' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Ziox' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Zopo' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('ZTE' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Zuk' , '["5"]' , '' , '');
insert into brands(name, Specialite, description, logo) values ('Zync' , '["5"]' , '' , '');





#electroplanet
insert into brands(name, description, logo) values ('Adata'  , '' , '');
insert into brands(name, description, logo) values ('Ariston'  , '' , '');
insert into brands(name, description, logo) values ('Allocacoc'  , '' , '');
insert into brands(name, description, logo) values ('Argo'  , '' , '');
insert into brands(name, description, logo) values ('Arthur Martin'  , '' , '');
insert into brands(name, description, logo) values ('Avent'  , '' , '');
insert into brands(name, description, logo) values ('Awei'  , '' , '');
insert into brands(name, description, logo) values ('Aeg'  , '' , '');
insert into brands(name, description, logo) values ('Ariete'  , '' , '');
insert into brands(name, description, logo) values ('Abyx'  , '' , '');
insert into brands(name, description, logo) values ('Air Monster'  , '' , '');
insert into brands(name, description, logo) values ('Alaska'  , '' , '');
insert into brands(name, description, logo) values ('Arzum'  , '' , '');
insert into brands(name, description, logo) values ('Babyliss'  , '' , '');
insert into brands(name, description, logo) values ('Beko'  , '' , '');
insert into brands(name, description, logo) values ('Bosch'  , '' , '');
insert into brands(name, description, logo) values ('Braun'  , '' , '');
insert into brands(name, description, logo) values ('Brita'  , '' , '');
insert into brands(name, description, logo) values ('Beper'  , '' , '');
insert into brands(name, description, logo) values ('Base'  , '' , '');
insert into brands(name, description, logo) values ('Batitherm'  , '' , '');
insert into brands(name, description, logo) values ('Beats'  , '' , '');
insert into brands(name, description, logo) values ('Bose'  , '' , '');
insert into brands(name, description, logo) values ('Calor'  , '' , '');
insert into brands(name, description, logo) values ('Candy'  , '' , '');
insert into brands(name, description, logo) values ('Canon'  , '' , '');
insert into brands(name, description, logo) values ('Chaffoteaux'  , '' , '');
insert into brands(name, description, logo) values ('Cookart'  , '' , '');
insert into brands(name, description, logo) values ('Cellularline'  , '' , '');
insert into brands(name, description, logo) values ('Carrier'  , '' , '');
insert into brands(name, description, logo) values ('Delonghi'  , '' , '');
insert into brands(name, description, logo) values ('Dlink'  , '' , '');
insert into brands(name, description, logo) values ('Dyson'  , '' , '');
insert into brands(name, description, logo) values ('Dell'  , '' , '');
insert into brands(name, description, logo) values ('Eaton'  , '' , '');
insert into brands(name, description, logo) values ('Elexia'  , '' , '');
insert into brands(name, description, logo) values ('Epson'  , '' , '');
insert into brands(name, description, logo) values ('Easydis'  , '' , '');
insert into brands(name, description, logo) values ('Easymount'  , '' , '');
insert into brands(name, description, logo) values ('Energy Sistem'  , '' , '');
insert into brands(name, description, logo) values ('Express'  , '' , '');
insert into brands(name, description, logo) values ('Franke'  , '' , '');
insert into brands(name, description, logo) values ('Fujifilm'  , '' , '');
insert into brands(name, description, logo) values ('Funway'  , '' , '');
insert into brands(name, description, logo) values ('Foodsaver'  , '' , '');
insert into brands(name, description, logo) values ('Fosa'  , '' , '');
insert into brands(name, description, logo) values ('Goodis'  , '' , '');
insert into brands(name, description, logo) values ('Gopro'  , '' , '');
insert into brands(name, description, logo) values ('Galaxy'  , '' , '');
insert into brands(name, description, logo) values ('Haier'  , '' , '');
insert into brands(name, description, logo) values ('Havit'  , '' , '');
insert into brands(name, description, logo) values ('Homedics'  , '' , '');
insert into brands(name, description, logo) values ('Hoover'  , '' , '');
insert into brands(name, description, logo) values ('Hp'  , '' , '');
insert into brands(name, description, logo) values ('H.Koenig'  , '' , '');
insert into brands(name, description, logo) values ('Hikvison'  , '' , '');
insert into brands(name, description, logo) values ('Harman Kardon'  , '' , '');
insert into brands(name, description, logo) values ('Ibili'  , '' , '');
insert into brands(name, description, logo) values ('Imperial'  , '' , '');
insert into brands(name, description, logo) values ('Inoxibar'  , '' , '');
insert into brands(name, description, logo) values ('Indesit'  , '' , '');
insert into brands(name, description, logo) values ('Itimat'  , '' , '');
insert into brands(name, description, logo) values ('Irobot'  , '' , '');
insert into brands(name, description, logo) values ('Jata'  , '' , '');
insert into brands(name, description, logo) values ('Jbl'  , '' , '');
insert into brands(name, description, logo) values ('Junkers'  , '' , '');
insert into brands(name, description, logo) values ('Kenwood'  , '' , '');
insert into brands(name, description, logo) values ('Krohler'  , '' , '');
insert into brands(name, description, logo) values ('Krups'  , '' , '');
insert into brands(name, description, logo) values ('Kitchenaid'  , '' , '');
insert into brands(name, description, logo) values ('Kaspersky'  , '' , '');
insert into brands(name, description, logo) values ('Kioxia'  , '' , '');
insert into brands(name, description, logo) values ('Karcher'  , '' , '');
insert into brands(name, description, logo) values ('Kingston'  , '' , '');
insert into brands(name, description, logo) values ('Lg'  , '' , '');
insert into brands(name, description, logo) values ('Liebherr'  , '' , '');
insert into brands(name, description, logo) values ('Logicom'  , '' , '');
insert into brands(name, description, logo) values ('Logitech'  , '' , '');
insert into brands(name, description, logo) values ('Magefesa'  , '' , '');
insert into brands(name, description, logo) values ('Magimix'  , '' , '');
insert into brands(name, description, logo) values ('Moulinex'  , '' , '');
insert into brands(name, description, logo) values ('Media Range'  , '' , '');
insert into brands(name, description, logo) values ('Msi'  , '' , '');
insert into brands(name, description, logo) values ('Nespresso'  , '' , '');
insert into brands(name, description, logo) values ('Nikon'  , '' , '');
insert into brands(name, description, logo) values ('Nintendo'  , '' , '');
insert into brands(name, description, logo) values ('Ngs'  , '' , '');
insert into brands(name, description, logo) values ('No Name'  , '' , '');
insert into brands(name, description, logo) values ('Optiline'  , '' , '');
insert into brands(name, description, logo) values ('Oraimo'  , '' , '');
insert into brands(name, description, logo) values ('Playstation'  , '' , '');
insert into brands(name, description, logo) values ('Pinacle'  , '' , '');
insert into brands(name, description, logo) values ('Pioneer'  , '' , '');
insert into brands(name, description, logo) values ('Rowenta'  , '' , '');
insert into brands(name, description, logo) values ('Royal'  , '' , '');
insert into brands(name, description, logo) values ('Roline'  , '' , '');
insert into brands(name, description, logo) values ('Rivacase'  , '' , '');
insert into brands(name, description, logo) values ('Remade'  , '' , '');
insert into brands(name, description, logo) values ('Risoli'  , '' , '');
insert into brands(name, description, logo) values ('Sandisk'  , '' , '');
insert into brands(name, description, logo) values ('Seb'  , '' , '');
insert into brands(name, description, logo) values ('Severin'  , '' , '');
insert into brands(name, description, logo) values ('Siera'  , '' , '');
insert into brands(name, description, logo) values ('Simeo'  , '' , '');
insert into brands(name, description, logo) values ('Soehnle'  , '' , '');
insert into brands(name, description, logo) values ('Sandberg'  , '' , '');
insert into brands(name, description, logo) values ('Sonorous'  , '' , '');
insert into brands(name, description, logo) values ('Steamone'  , '' , '');
insert into brands(name, description, logo) values ('Solac'  , '' , '');
insert into brands(name, description, logo) values ('Stg'  , '' , '');
insert into brands(name, description, logo) values ('Skyworth'  , '' , '');
insert into brands(name, description, logo) values ('Sencor'  , '' , '');
insert into brands(name, description, logo) values ('Spirit Of Gamer'  , '' , '');
insert into brands(name, description, logo) values ('Targus'  , '' , '');
insert into brands(name, description, logo) values ('Taurus'  , '' , '');
insert into brands(name, description, logo) values ('Tcl'  , '' , '');
insert into brands(name, description, logo) values ('Tefal'  , '' , '');
insert into brands(name, description, logo) values ('Tenda'  , '' , '');
insert into brands(name, description, logo) values ('Thomson'  , '' , '');
insert into brands(name, description, logo) values ('Tnb'  , '' , '');
insert into brands(name, description, logo) values ('Toshiba'  , '' , '');
insert into brands(name, description, logo) values ('Tplink'  , '' , '');
insert into brands(name, description, logo) values ('Trust'  , '' , '');
insert into brands(name, description, logo) values ('Terraillon'  , '' , '');
insert into brands(name, description, logo) values ('Tp-Link'  , '' , '');
insert into brands(name, description, logo) values ('Trend'  , '' , '');
insert into brands(name, description, logo) values ('Urban Factory'  , '' , '');
insert into brands(name, description, logo) values ('Ufesa'  , '' , '');
insert into brands(name, description, logo) values ('Valira'  , '' , '');
insert into brands(name, description, logo) values ('Vision'  , '' , '');
insert into brands(name, description, logo) values ('Value'  , '' , '');
insert into brands(name, description, logo) values ('Vitrinor'  , '' , '');
insert into brands(name, description, logo) values ('Western Digital'  , '' , '');
insert into brands(name, description, logo) values ('Whirlpool'  , '' , '');
insert into brands(name, description, logo) values ('Wiko'  , '' , '');
insert into brands(name, description, logo) values ('W-Pro'  , '' , '');
insert into brands(name, description, logo) values ('Wpro'  , '' , '');
insert into brands(name, description, logo) values ('Yamaha'  , '' , '');
insert into brands(name, description, logo) values ('Zanussi'  , '' , '');